### ISSUE TITLE
Веб хуки / Нет смысла продолжать эту тему т.к разрабу нет дела)

### ISSUE THREAD

**Issue by TheQmaks** [Shnapik/Qiwi-Api-Class-PHP#5]
Планируется ли добавление веб-хуков?

**Comment by Shnapik** [comment]
День добрый, да конечно же. Писал в блоге об этом. Теперь время более менее появилось, на днях будет обновление класса я думаю, если ничего не поменяется. Если поменяется всё же, то крайний случай - выходные. Но скорее всего в ближайшие 2 дня всё будет.

**Comment by Shnapik** [comment]
Обновление будет все же в эти выходные. Либо сегодня, либо завтра. Раньше не получалось со временем.

**Comment by TheQmaks** [comment]
Мертв?)

**Comment by Shnapik** [comment]
Ответ получил от тех. поддержки. Буду теперь обновлять класс, пока трудно сказать когда точно, но в сентябре 100%. Веб-хуки пока сыроваты у киви...

**Comment by TheQmaks** [comment]
Дороу, ты там как? Ждать обновы?)

**Comment by Shnapik** [comment]
Вечер добрый, да обновление будет. Но пока тону в заказах и в работе в частности, как только так сразу. :(

**Comment by TheQmaks** [comment]
> А я баланс получить не могу. :( Возвращает NULL.

А ты права токену выдал на получение баланса?

**Comment by Rambuto** [comment]
Добрый вечер. Есть продвижение ?
Может нужна кака я та помощь

**Comment by MrFallen** [comment]
> > А я баланс получить не могу. :( Возвращает NULL.
> 
> А ты права токену выдал на получение баланса?

Решил проблему. Неправильно тянул информацию из JSON.
